const wait=duration=>new Promise(resolve=>setTimeout(resolve,duration));
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const messageTime=()=>new Intl.DateTimeFormat('ar-KW',{hour:'numeric',minute:'2-digit'}).format(new Date());
const businesses={
salon:{icon:'💇‍♀️',name:'صالون لافندر',short:'صالون تجميل',hours:'يومياً · ١٠ ص – ٩ م',location:'السالمية، شارع سالم المبارك',female:true,accent:'#c7459b',suggestions:['كم سعر البروتين؟','أبي أحجز موعد','عندكم عروض؟','وين موقعكم؟'],reply:'حياج الله 🌷 بروتين الشعر يبدأ من ٤٥ د.ك حسب طول وكثافة الشعر، ويشمل الاستشارة والسشوار.',service:'بروتين شعر',price:'٤٥ د.ك',day:'الثلاثاء',time:'٥:٠٠ مساءً'},
dental:{icon:'🦷',name:'عيادة الابتسامة التجريبية',short:'عيادة أسنان',hours:'السبت – الخميس · ٩ ص – ٩ م',location:'حولي، شارع بيروت',accent:'#4169ff',suggestions:['أبي تبييض أسنان','أبي أحجز اليوم','كم سعر الزراعة؟','وين موقعكم؟'],reply:'حياك الله 🌷 تبييض الأسنان بالعيادة يبدأ من ٧٥ د.ك، والطبيب يتأكد أول إن الخدمة مناسبة لك.',service:'تبييض أسنان',price:'٧٥ د.ك',day:'اليوم',time:'٦:٣٠ مساءً'},
laundry:{icon:'👔',name:'مصبغة نقي',short:'مغسلة ملابس',hours:'يومياً · ٨ ص – ١١ م',location:'توصيل لكل مناطق الكويت',accent:'#00aeca',suggestions:['عندكم استلام وتوصيل؟','شكثر الأسعار؟','متى يخلص الطلب؟','أبي أطلب استلام'],reply:'أكيد، عندنا استلام وتوصيل لباب البيت 🚚 الغسيل والكوي يبدأ من ٠٫٧٥٠ د.ك للقطعة، والطلب العادي يخلص خلال ٤٨ ساعة.',service:'استلام وغسيل ١٠ قطع',price:'يبدأ من ٧٫٥ د.ك',day:'اليوم',time:'٧:٠٠ مساءً'},
carwash:{icon:'🚗',name:'لمعة كار كير',short:'مغسلة سيارات',hours:'يومياً · ٧ ص – ١٢ ص',location:'الشويخ الصناعية',accent:'#6047ff',suggestions:['كم الغسيل الكامل؟','عندكم تلميع؟','أبي أحجز','وين موقعكم؟'],reply:'حياك الله ✨ الغسيل الكامل للصالون والهيكل يبدأ من ٨ د.ك، ويأخذ تقريباً ٤٥ دقيقة.',service:'غسيل كامل',price:'٨ د.ك',day:'اليوم',time:'٨:٠٠ مساءً'},
clinic:{icon:'🏥',name:'مركز عافية الطبي',short:'عيادة طبية',hours:'الأحد – الخميس · ٨ ص – ١٠ م',location:'الجابرية، قطعة ٣',accent:'#15a978',suggestions:['أبي أحجز اليوم','شنو التخصصات؟','متى دوامكم؟','وين موقعكم؟'],reply:'حياك الله 🌷 عندنا طب عام، جلدية، وأطفال. أقدر أرتب لك أقرب موعد متاح اليوم.',service:'استشارة طب عام',price:'٢٠ د.ك',day:'اليوم',time:'٤:٣٠ مساءً'},
restaurant:{icon:'🍽️',name:'دار فريج',short:'مطعم',hours:'يومياً · ١٢ م – ١٢ ص',location:'المباركية، سوق الغربللي',accent:'#e47b35',suggestions:['عندكم حجز طاولات؟','شنو طبقكم المميز؟','أبي أحجز اليوم','وين موقعكم؟'],reply:'حياك الله 🌷 طبقنا المميز مجبوس الدجاج، وعندنا حجز طاولات للعوايل والمجموعات.',service:'طاولة لـ ٤ أشخاص',price:'بدون رسوم حجز',day:'اليوم',time:'٨:٣٠ مساءً'}};
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const screens=$$('.experience-screen'),progressSteps=$$('.experience-progress span'),grid=$('#businessGrid'),conversation=$('#demoConversation'),suggestions=$('#quickSuggestions'),suggestionWrap=$('#suggestionWrap'),presence=$('#chatPresence');
let business,run=0;
Object.entries(businesses).forEach(([key,item])=>{const button=document.createElement('button');button.type='button';button.className='business-card';button.innerHTML=`<span>${item.icon}</span><strong>${item.short}</strong><small>جرّب الآن ←</small>`;button.onclick=()=>selectBusiness(key);grid.append(button);});
function showScreen(name){const index=['welcome','business','chat'].indexOf(name);screens.forEach(screen=>screen.classList.toggle('active',screen.dataset.screen===name));progressSteps.forEach((step,i)=>step.classList.toggle('active',i<=index));$('.experience-shell').scrollIntoView({behavior:reducedMotion?'auto':'smooth',block:'center'});}
$('#startExperience').onclick=()=>showScreen('business');$$('[data-back]').forEach(button=>button.onclick=()=>{run++;showScreen(button.dataset.back);});
function selectBusiness(key){business=businesses[key];document.documentElement.style.setProperty('--demo-accent',business.accent);$('#contextIcon').textContent=$('#chatAvatar').textContent=business.icon;$('#contextName').textContent=$('#chatBusinessName').textContent=business.name;$('#contextHours').textContent=business.hours;$('#contextLocation').textContent=business.location;conversation.innerHTML='<span class="wa-date">اليوم</span><div class="wa-security">🔒 الرسائل مشفّرة بين الطرفين</div>';suggestions.innerHTML='';business.suggestions.forEach((label,index)=>{const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=()=>startJourney(label,index);suggestions.append(button);});setJourney(0,'ابدأ بسؤال');suggestionWrap.hidden=false;presence.textContent='متصل الآن';showScreen('chat');setTimeout(()=>addMessage('assistant',business.female?'حياج الله 🌷 شلون أقدر أساعدج؟':'حياك الله 🌷 شلون أقدر أساعدك؟'),250);}
function setJourney(percent,label){$('#journeyProgress').style.width=`${percent}%`;$('#journeyLabel').textContent=label;}
function scrollChat(){conversation.scrollTo({top:conversation.scrollHeight,behavior:reducedMotion?'auto':'smooth'});}
function addMessage(role,html,kind=''){const item=document.createElement('div');item.className=`wa-message ${role} ${kind}`;item.innerHTML=`<span>${html}</span><time>${messageTime()} ${role==='assistant'?'✓✓':''}</time>`;conversation.append(item);scrollChat();}
async function reply(id,html,kind=''){if(id!==run)return false;presence.textContent='يكتب الآن...';const typing=document.createElement('div');typing.className='wa-typing';typing.innerHTML='<i></i><i></i><i></i>';conversation.append(typing);scrollChat();await wait(reducedMotion?50:Math.min(800,400+html.length*4));if(id!==run)return false;typing.remove();presence.textContent='متصل الآن';addMessage('assistant',html,kind);await wait(reducedMotion?50:280);return id===run;}
async function startJourney(question,index){const id=++run;suggestions.querySelectorAll('button').forEach(button=>button.disabled=true);suggestionWrap.hidden=true;addMessage('customer',question);setJourney(20,'رد فوري');await wait(180);if(question.includes('وين')){if(!await reply(id,`موقعنا في ${business.location} 📍<br><button class="inline-link" type="button">فتح الموقع على الخريطة ↗</button>`))return;}else if(!await reply(id,business.reply))return;setJourney(42,'السعر والخدمة');if(index===2&&!question.includes('أحجز'))if(!await reply(id,`وعندنا عرض هالأسبوع على ${business.service}: <strong>${business.price}</strong>. إذا تحب أقدر أحجز لك الحين.`))return;if(!await reply(id,business.female?'تبين أحجز لج أقرب موعد؟':'تبي أحجز لك أقرب موعد؟'))return;addChoices(id);}
function addChoices(id){const choices=document.createElement('div');choices.className='wa-choices';['أكيد، احجز لي','لا، أبي موظفة'].forEach((label,index)=>{const button=document.createElement('button');button.type='button';button.textContent=business.female?label.replace('احجز','احجزي'):label;button.onclick=()=>{choices.remove();index?humanHandoff(id):bookingFlow(id);};choices.append(button);});conversation.append(choices);scrollChat();}
async function bookingFlow(id){addMessage('customer',business.female?'أكيد، احجزي لي':'أكيد، احجز لي');setJourney(58,'جمع التفاصيل');if(!await reply(id,'أكيد. شنو الاسم ورقم التلفون؟'))return;addMessage('customer',business.female?'نورة سالم · ٥٥٥٠ ١٢٣٤':'عبدالله سالم · ٥٥٥٠ ١٢٣٤');if(!await reply(id,`يعطيك العافية. المتاح ${business.day}: <strong>${business.time}</strong>. مناسب؟`))return;const confirm=document.createElement('div');confirm.className='wa-choices single';confirm.innerHTML='<button type="button">إي، مناسب</button>';conversation.append(confirm);scrollChat();confirm.querySelector('button').onclick=async()=>{confirm.remove();addMessage('customer','إي، مناسب');setJourney(78,'تأكيد الحجز');if(!await reply(id,`<div class="booking-success"><b>✓</b><h4>تم تأكيد الحجز</h4><dl><dt>الخدمة</dt><dd>${business.service}</dd><dt>الموعد</dt><dd>${business.day} · ${business.time}</dd><dt>الاسم</dt><dd>${business.female?'نورة سالم':'عبدالله سالم'}</dd></dl><p>شكراً لك 🌷</p></div>`,'success'))return;humanHandoff(id,true);};}
async function humanHandoff(id,afterBooking=false){if(!afterBooking)addMessage('customer','أبي أكلم موظفة الاستقبال');setJourney(90,'فريقك موجود عند الحاجة');if(!await reply(id,'أكيد، إذا حبيت أقدر أحولك مباشرة لموظفة الاستقبال. بيكون عندها ملخص المحادثة كامل 🙋‍♀️'))return;setJourney(100,'اكتملت التجربة');await wait(250);showConversion();}
function showConversion(){const card=document.createElement('div');card.className='conversion-card';card.innerHTML=`<span>✦</span><h4>هل أعجبتك التجربة؟</h4><p>تخيل هذا النظام يرد على عملائك ويحجز لهم ٢٤ ساعة يومياً.</p><a href="#contact" class="conversion-primary">احجز عرض مجاني</a><a href="https://wa.me/201555277179?text=${encodeURIComponent('مرحباً، أريد تجربة Sawely لنشاطي')}" target="_blank" rel="noopener noreferrer" class="conversion-whatsapp">تواصل عبر واتساب</a><button type="button">↻ جرّب نشاط ثاني</button>`;conversation.append(card);scrollChat();card.querySelector('button').onclick=()=>showScreen('business');}
const sectionLinks=$$('.nav nav a[href^="#"]');sectionLinks.forEach(link=>link.onclick=event=>{const section=$(link.getAttribute('href'));if(!section)return;event.preventDefault();section.scrollIntoView({behavior:reducedMotion?'auto':'smooth'});history.replaceState(null,'',link.getAttribute('href'));});
if(!reducedMotion&&'IntersectionObserver'in window){const targets=$$('.metric-grid article,.steps article,.benefit-grid article,.section-head,.dashboard-window,.experience-shell,.cta>div');document.body.classList.add('reveal-ready');targets.forEach((target,index)=>{target.dataset.reveal='';target.style.setProperty('--reveal-delay',`${Math.min(index%6,5)*70}ms`);});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.1});targets.forEach(target=>observer.observe(target));}
const phoneConversation=$('#phoneConversation'),phoneReplay=$('#phoneReplay'),phonePresence=$('#phonePresence');let phoneRun=0;
function phoneMessage(role,text,extra=''){const message=document.createElement('p');message.className=`bubble ${role} ${extra}`;message.innerHTML=`${text}<time>${messageTime()}${role==='outgoing'?' ✓✓':''}</time>`;phoneConversation.append(message);phoneConversation.scrollTo({top:phoneConversation.scrollHeight,behavior:'smooth'});}
async function phoneReply(id,text,extra=''){if(id!==phoneRun)return false;phonePresence.textContent='يكتب الآن...';const typing=document.createElement('div');typing.className='phone-typing';typing.innerHTML='<i></i><i></i><i></i>';phoneConversation.append(typing);await wait(reducedMotion?50:580);if(id!==phoneRun)return false;typing.remove();phonePresence.textContent='متصل الآن';phoneMessage('outgoing',text,extra);await wait(260);return true;}
async function playPhoneConversation(){const id=++phoneRun;phoneConversation.innerHTML='<span class="chat-date">اليوم</span>';phoneReplay.disabled=true;phoneMessage('incoming','السلام عليكم، أبي تنظيف اليوم بعد ٦. شكثر السعر؟');await wait(180);if(!await phoneReply(id,'وعليكم السلام، حياك الله 👋 سعر التنظيف ٢٥ د.ك، وعندنا ٦:٣٠ م متاح.'))return;phoneMessage('incoming','ممتاز، احجز لي. عبدالله · ٥٥٥٠ ١٢٣٤');await wait(180);await phoneReply(id,'✅ <strong>تم تأكيد الحجز</strong><br>تنظيف أسنان · اليوم ٦:٣٠ م<br>بنذكّرك قبل الموعد. شكراً لك 🌷','accent phone-confirmation');phoneReplay.disabled=false;}
phoneReplay?.addEventListener('click',playPhoneConversation);if(phoneConversation)setTimeout(playPhoneConversation,500);
